name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '.github/workflows/*.yaml'
      - '!.github/workflows/test.yaml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.4', '3.3', '3.2', '3.1']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
